"""Terminal skins generated from coords:  python -m <package path>.ginseng_rice.skins [out_dir]"""
from __future__ import annotations

import sys
from pathlib import Path

from .oklab import hex_to_oklab, oklab_to_hex
from .tokens import Coord, load_all

HEADER = "generated by ginseng_rice.skins from coords/{name}.toml; edit the TOML and regenerate"


def _lift(hex_color: str, amount: float) -> str:
    L, a, b = hex_to_oklab(hex_color)
    return oklab_to_hex(min(1.0, max(0.0, L + amount)), a, b)


def ansi16(coord: Coord) -> list[str]:
    """ANSI colors 0-15. Red, green and yellow carry short, safe and thin so shell tools agree with the TUI."""
    p = coord.palette
    if coord.dark:
        black, white, bright_black, bright_white, lift = p["panel"], p["muted"], p["rule"], p["ink"], 0.07
    else:
        black, white, bright_black, bright_white, lift = p["ink"], p["rule"], p["muted"], p["panel"], -0.07
    hues = [p["short"], p["safe"], p["thin"], p["focus"], p["opt_liquidate"], p["opt_credit"]]
    return [black, *hues, white, bright_black, *(_lift(color, lift) for color in hues), bright_white]


def ghostty(coord: Coord) -> str:
    p = coord.palette
    lines = [f"# {HEADER.format(name=coord.name)}",
             f"background = {p['paper']}", f"foreground = {p['ink']}", f"cursor-color = {p['focus']}",
             f"selection-background = {p['band_inner']}", f"selection-foreground = {p['ink']}"]
    lines += [f"palette = {i}={color}" for i, color in enumerate(ansi16(coord))]
    return "\n".join(lines) + "\n"


def kitty(coord: Coord) -> str:
    p = coord.palette
    lines = [f"# {HEADER.format(name=coord.name)}",
             f"foreground {p['ink']}", f"background {p['paper']}", f"cursor {p['focus']}",
             f"cursor_text_color {p['paper']}", f"selection_foreground {p['ink']}",
             f"selection_background {p['band_inner']}"]
    lines += [f"color{i} {color}" for i, color in enumerate(ansi16(coord))]
    return "\n".join(lines) + "\n"


def write(out_dir: Path) -> list[Path]:
    written = []
    for coord in load_all().values():
        for folder, filename, text in (("ghostty", f"ginseng-{coord.name}", ghostty(coord)),
                                       ("kitty", f"ginseng-{coord.name}.conf", kitty(coord))):
            path = out_dir / folder / filename
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            written.append(path)
    return written


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "skins"
    for path in write(target):
        print("wrote", path)
