"""One confirmed addition tool; preparing a proposal never writes the workspace."""

from __future__ import annotations

from datetime import date
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from ginseng.workspace import (
    CashAccount,
    CashBill,
    SaveWorkspaceRequest,
)
from ginseng.finance_models import FinanceWorkspace
from ginseng.personal_forecast import evaluate_personal_forecast


def _addition_schema(model: type[BaseModel]) -> dict[str, Any]:
    # Keep the tool's fields aligned with the existing save validators, but IDs
    # are generated by the server, never accepted from the model.
    schema = model.model_json_schema()
    del schema["properties"]["id"]
    schema["required"].remove("id")
    return schema


# JSON Schema supports numeric enums; Gemini's older `parameters` Schema only
# supports string enums. https://ai.google.dev/api/generate-content#FunctionDeclaration
ADDITIONS_TOOL = {
    "name": "propose_workspace_additions",
    "description": (
        "Prepare ONE combined preview of all requested NEW accounts and bills. "
        "Does not save anything: the user must approve. All amounts are exact integer "
        "USD cents (2000 dollars = 200000 cents). Ask for missing details first. "
        "Do not include already saved items. The server calculates the cash schedule."
    ),
    "parametersJsonSchema": {
        "type": "object",
        "additionalProperties": False,
        "required": ["accounts", "bills", "horizon_days"],
        "properties": {
            "accounts": {"type": "array", "maxItems": 50, "items": _addition_schema(CashAccount)},
            "bills": {"type": "array", "maxItems": 200, "items": _addition_schema(CashBill)},
            "horizon_days": {"type": "integer", "enum": [14, 30, 60]},
        },
    },
}


class _Additions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    accounts: list[dict[str, Any]] = Field(max_length=50)
    bills: list[dict[str, Any]] = Field(max_length=200)
    horizon_days: Literal[14, 30, 60]


def build_additions_proposal(arguments: dict[str, Any], workspace: FinanceWorkspace) -> dict[str, Any]:
    additions = _Additions.model_validate(arguments)
    if not additions.accounts and not additions.bills:
        raise ValueError("Specify at least one new account or bill.")
    if any("id" in item for item in (*additions.accounts, *additions.bills)):
        raise ValueError("Additions cannot specify existing record IDs.")
    accounts = [CashAccount(id=uuid4(), **item) for item in additions.accounts]
    bills = [CashBill(id=uuid4(), **item) for item in additions.bills]

    seen_accounts = {(item.name.casefold(), item.kind, item.balance_cents) for item in workspace.accounts}
    for account in accounts:
        key = (account.name.casefold(), account.kind, account.balance_cents)
        if key in seen_accounts:
            raise ValueError(f'An identical account named "{account.name}" is already included. Use a distinct name for a different account.')
        seen_accounts.add(key)
    seen_bills = {(item.label.casefold(), item.amount_cents, item.due_date) for item in workspace.bills}
    for bill in bills:
        key = (bill.label.casefold(), bill.amount_cents, bill.due_date)
        if key in seen_bills:
            raise ValueError(f'An identical bill named "{bill.label}" is already included. Use a distinct label for a different bill.')
        seen_bills.add(key)

    draft = SaveWorkspaceRequest(
        expected_revision=workspace.revision,
        as_of=workspace.as_of or date.today(),
        accounts=[*workspace.accounts, *accounts],
        bills=[*workspace.bills, *bills],
    )
    preview_workspace = workspace.model_copy(update={
        "as_of": draft.as_of, "accounts": draft.accounts, "bills": draft.bills,
        "inputs": workspace.inputs.model_copy(update={"mode": "scheduled"}),
    })
    projection = None
    projection_error = None
    try:
        run = evaluate_personal_forecast(preview_workspace, additions.horizon_days)
        if run.result is None:
            raise ValueError("; ".join(requirement.label for requirement in run.requirements))
        result = run.result
        opening = sum(account.balance_cents for account in preview_workspace.accounts)
        balances = [opening, *[round(value * 100) for value in result.cash_paths.p50]]
        scheduled_bills = result.cash_paths.known_obligations
        projection = {
            "opening_balance_cents": opening,
            "scheduled_bills_cents": round(scheduled_bills[-1] * 100) if scheduled_bills else 0,
            "ending_balance_cents": balances[-1],
            "lowest_balance_cents": min(balances),
            "additional_cash_needed_cents": max(0, -min(balances)),
        }
    except ValueError as error:
        projection_error = str(error)
    return {
        "draft": draft.model_dump(mode="json"),
        "added_account_ids": [str(account.id) for account in accounts],
        "added_bill_ids": [str(bill.id) for bill in bills],
        "horizon_days": additions.horizon_days,
        "projection": projection,
        "projection_error": projection_error,
    }
